; Настройки системы; синхронизируются в github
; Для конфигурирования системы для отдельной машины/копии рекомендуется
; скопировать данный файл в ModelConfig.local.ini

[DEFAULT]
LOG_FORMAT = deepseek_ocr_%d%m%Y_%H%M.log

# Программа будет загружать модель c hugginface вместо локального хранилища
# yes/no
FORCE_DOWNLOAD = no

# Повторно сканирует директорию 'raw_files' через заданные интервалы
# yes/no
CYCLE_PARSING = no

# Интервал (секунды) между повторным сканированием
CYCLE_INTERVAL = 300

# Освобождает ресурсы GPU во время простоя
# yes/no
FREE_GPU = yes

# Поддерживаемые типы файлов 
# yes/no
PARSE_PDF = yes
PARSE_PNG = yes
PARSE_JPG = yes

# Настройки движка OCR
MODEL_NAME = deepseek-ai/deepseek-ocr-model
LOCAL_MODEL_PATH = models/deepseek
LOCAL_TOKEN_PATH = models/deepseek0_token

; Пример настройки движка OCR
; [Engines]
; enabled = deepseek0

; [DeepSeek.deepseek0]
; MODEL_NAME = your/deepseek-ocr-model
; LOCAL_MODEL_PATH = models/deepseek0
; LOCAL_TOKEN_PATH = models/deepseek0_token
; FORCE_DOWNLOAD = no
; DEVICE = cuda:0

